### PR TITLE
T47

### LINKED ISSUE #52: Add trace representation for implicit exceptions?
If I say

```
1 + (2/0)
```
then this will implicitly raise a "Division by zero" exception. This exception is not recorded in a trace in any way, which makes it impossible for `isExn` to spot a raised exception. I wonder when does this become a problem, ie. when does this cause incorrect results. I'm unable to construct any testcase that would expose practical ramifications of this potential bug (possibly due to #47?)

### PR DESCRIPTION
**Pull request by jamescheney**
fixes #52 and #47.

### CODE REVIEW

File: lib/Language/Slicer/Slice.hs [hunk 1]
```diff
@@ -244,5 +249,16 @@ bwdSliceM outcome trace = do
                rho2' = unbindEnv  rho2 x
            (rho1, e1, t1') <- bwdSliceM (OExn p1) t1
            return (rho1 `lub` rho2', ETryWith e1 x e2, TTryWith t1' x t2')
+
+    -- JSTOLAREK: hacking OHole rules
```
Comment (jstolarek) [inline lib/Language/Slicer/Slice.hs:253]: Allow me only to remark that I don't feel very confident at this part of code.

Comment (jamescheney) [reply lib/Language/Slicer/Slice.hs:253]: Yes, I'll take a closer look at that.  That's one reason I wanted to merge first so that I don't make changes that conflict with the concurrent changes to Slice.hs.  I'll merge once the tests pass.

Comment (jstolarek) [reply lib/Language/Slicer/Slice.hs:253]: >  That's one reason I wanted to merge first so that I don't make changes that conflict with the concurrent changes to Slice.hs

Yes. That's precisely why I suggested yesterday to start from my branch :-)
